# Select the type of API version and type of service/object

apiVersion: v1

kind: Service

# Metadata for name

metadata:
  name: node-app-svc

  namespace: default # sre

# Specificaition to include ports Selector to connecto to the deployment

spec:
  ports:
    - nodePort: 30443 # range is 30000-32768

      port: 3000

      protocol: TCP

      targetPort: 3000

  # Let's define the selector and label to connect to nginx deployment

  selector:
    app: node-app # this label connects this service to deployment

  # Creating NodePort type of deployment

  type: NodePort # also use LoadBalancer -  for local use cluster IP
