---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment # naming the deployment
spec:
  selector:
    matchLabels:
      app: node-app # look for this label to match with k8 service

  # Let's create a replica set of this with 3 instances/pods
  replicas:
    3
    # template to use it's label for k8 service to launch in the browser
  template:
    metadata:
      labels:
        app: node-app # this label connects to the service or any other k8 components
    # Let's define the container spec
    spec:
      containers:
        - name: node-app
          image: fatemazahra/eng122_node_app:latest
          ports:
            - containerPort: 3000
# create a kubernetes nginx-service.yml to create a k8 service
